# Redes Neurais Artificiais

Muito se pensa sobre como os seres humanos conseguiram evoluir, pensar, aprender. Essa investigação levou ao descobrimento do sistema nervoso humano, que é composto por uma rede conectada de neurônios.

![alt text](https://static.mundoeducacao.bol.uol.com.br/mundoeducacao/2019/10/1-partes-do-neuronio.jpg)

O neurônio é um tipo específico de célula que tem como função principal transmitir impulsos nervosos. Podemos resumir sua estruturas principais em dendritos, corpo celular e axônio. Os dendritos são responsáveis por conectar o nosso neurônio a outros neurônios. Quando um impulso chega a um dendrito ele transmite esse impulso para o corpo celular que em seguida passa para o axônio e este então passa o impulso para frente, criando assim uma rede conectada.

Mas se o neurônio só passa informações para frente, como eles seriam responsáveis pela nossa inteligência? 

Uma questão que ainda não tem respostas muito definidas pela ciência é a capacidade do neurônio de aprender e de alguma forma selecionar o impulso que ele acha importante passar para frente, intensificar ou suprimir. É dessa forma que são criados caminhos de comunicação no nosso sistema nervoso, que quando bem treinado consegue reconhecer muito bem os padrões estabelecidos.

Depois de entender como funcionam as redes neurais biológicas, os cientistas começaram a tentar reproduzir esse comportamento em um modelo matemático que conseguisse aprender assim como um ser humano. 

## Perceptron

O [Perceptron](http://deeplearningbook.com.br/o-perceptron-parte-1/), desenvolvido pelo cientista Frank Rosenblatt, foi um dos primeiros modelos propostos para resolver essa questão.


<img src="perceptron.png" alt="drawing" width="500"/>


Nesse modelo, a saída é o resultado de:

$$ Saida=\begin{cases} 0,\quad se\quad \sum _{ i=1 }^{ n }{ { x }_{ i }{ w }_{ i } \le  limiar }  \\ 1,\quad se\quad \sum _{ i=1 }^{ n }{ { x }_{ i }{ w }_{ i } > limiar }  \end{cases} $$


Fazendo um paralelo com o neurônio humano, os impulsos que chegam dos neunônios vizinhos são os Xi, os dendritos podem ser comparados com os pesos Wi, o corpo celular faz o somatório e aplica o limiar e o axônio transmite a saída que será entrada do próximo neurônio na rede.

A equação do perceptron pode ser reescrita como:

$$ Saida=\begin{cases} 0,\quad se\quad x\cdot w-b\le 0 \\ 1,\quad se\quad x\cdot w-b>0\quad  \end{cases} $$

Em que o produdo de x por w é o produto escalar dos vetores de entrada e de pesos e b é o bias do perceptron, que representa o limiar da equação anterior.






O [modelo de neurônio](http://deeplearningbook.com.br/o-neuronio-biologico-e-matematico/) mais utilizado nas redes neurais modernas é um pouco diferente do perceptron. E permite a utilização de uma função de ativação, que tem grande importância na etapa de treinamento da rede.

Sendo assim, o modelo matemático do neurônio fica:

$$ Saida=f\left( \left( \sum _{ i=1 }^{ n }{ { x }_{ i }{ w }_{ i } }  \right) +b \right) $$

Em que f é a função de ativação.



## Redes Neurais

Para que o algoritmo possa aprender padrões complexos de um conjunto de dados, muitas vezes um perceptron não é suficiente. Assim, são criadas redes neurais que são conjuntos de neurônios interligados.


<img src="https://lamfo-unb.github.io/img/simple_DNN/RNA1.png" alt="drawing" width="500"/>

A imagem acima representa um rede neural de três camadas. A camada mais à esquerda (verde) é chamada de camada de entrada. A mais à direita (vermelha) é chamada de camada de saída, que, nesse caso, contém apenas um neurônio. A camada do meio (azul) é chamada de camada oculta, que significa simplesmente que essa camada não é entrada nem saída. A rede acima possui penas uma camada oculta, mas existem redes que possuem múltiplas camadas ocultas.

O design das camadas de entrada e saída é bem direto. Por exemplo, suponha que queremos determinar se, dadas condições, vai chover ou não. Os atributos são: umidade do ar, temperatura, época do ano e quantidade de nuvens no céu. Uma forma natural de projetar essa rede é codificar os valores numéricos dos atributos nos neurônios de entrada. Como são quatro atributos, serão quatro neurônios de entrada. A camada de saída irá conter apenas um neurônio com valores inferiores a 0,5 indicando que não vai chover e valores superiores a 0,5 indicando que vai chover.

O design das camadas ocultas é mais variado e pesquisadores de redes neurais desenvolveram várias heurísticas para o design dessas camadas para que a rede possua o comportamento desejado.

### Redes Neurais Feed-Forward
As redes neurais feed-foward são as mais comuns na prática. Nelas, a primeira camada é a de entrada e a última a de saída. Se houver mais de uma camada oculta, são chamadas de redes neurais profundas. Nesse modelo, a saída de uma camada é sempre entrada da camada seguinte, ou seja, não existem loops na rede. As atividades dos neurônios em cada camada são uma função não-linear das atividades na camada anterior.

<img src="https://static.imasters.com.br/wp-content/uploads/2017/09/1-1.png" alt="drawing" width="300"/>


As redes neurais multicamadas tratam-se dos casos em que a camada oculta da rede, já descrita anteriormente, é formada por inúmeras camadas. Em outras palavras, são arquiteturas onde os neurônios são organizados em duas ou mais camadas de processamento (camadas ocultas), já que sempre vai existir pelo menos uma camada de entrada e uma camada de saída. Construindo-se, assim, uma verdadeira grande rede de camadas de neurônios para que seja  possível tratar problemas baseados em dados que não são linearmente separáveis.


#### Separação de Dados: Linear x Não-Linear

Dados considerados linearmente separáveis são ditos dados que, se representados em um gráfico de duas dimensões, será possível traçar uma reta que separe as classes. Para ilustrar, temos a imagem abaixo, em que é possível traçar, fácilmente, uma reta que separa as duas classes apresentadas.

Para esse tipo de dataset, redes neurais com apenas uma única camada oculta conseguem desempenhar bons resultados, tendo em vista a certa simplicidade do problema.

![Linearmente separável](https://jamesmccaffrey.files.wordpress.com/2019/04/linearly_sep_data.jpg?w=900)


Por outro lado, dados considerados não-linearmente separáveis apresentam uma disposição de classes, quando representados em um gráfico, em que não se torna possível a distinção das mesmas apenas com uma reta. Como ilustrado abaixo, para separação das classes, temos que o gráfico à esquerda necessitaria de duas retas, enquanto que o à direita necessitaria de uma curva.

Já nesse caso, a aplicação de uma rede neural com apenas uma única camada oculta não é satisfatória. Pelo aumento de complexidade, a acurácia de um rede de única camada decai significativamente.

![não-linearmente separável](https://jamesmccaffrey.files.wordpress.com/2019/04/linearly_sep_data_not.jpg?w=900)

#### Características

Como já citado, tal modelo é extremamente util para resolução de problemas não-lineares, tornando possível o desenvolvimento de estudos com desafios mais complexos.

Mas, isso também pode ser tratado como uma faca de dois gumes. Com o aumento da complexidade da rede, adicionando inúmeras camadas de processamento, aumenta-se, também, o nível de dificuldade para otimizá-la quando trabalho com datasets extremamente grandes. 

O simples ato de aumentar o número de camadas e neurônios pode não acarretar em uma melhora na acurácia das soluções. Uma das limitações dessa rede é que ao se aumentar muito o número de camadas e neurônios, ela tende a ficar com um número de parâmetros exagerado e, com isso, tão complexa e pesada a ponto do hardware ter dificuldades em processa-la e ela não convergir.

Outro fator é que esse tipo de rede possui uma função de perda não convexa, onde existe mais de um mínimo local. Portanto, diferentes inicializações de pesos aleatórios podem levar a uma precisão de validação diferente.



### Redes Neurais Recorrentes

Nesse modelo, a retroalimentação é possível. Essas redes podem ter uma dinâmica complicada, o que dificulta o treinamento, contudo, elas são mais biologicamente realistas. 

Nas redes recorrentes, a ideia é ter neurônios que disparem por um tempo limitado, estimulando outros neurônios que também disparem por tempo limitado. Dessa forma, ocorrerá uma cascata de disparos, fazendo com que loops não causem prejuízos à rede, uma vez que a saída de um neurônio afeta apenas sua entrada em algum momento posterior, não instantaneamente.

<img src="https://static.imasters.com.br/wp-content/uploads/2017/09/2-1.png" alt="drawing" width="300"/>

As redes neurais simétricas tratam-se de um caso particular das redes recorrentes em que as conexões entre as unidades são simétricas, ou seja, a matriz de conectividade é simétrica.

## Redes Neurais Convolucionais

Uma rede neural convolucional é um algoritmo de aprendizado de máquina muito usado para se trabalhar com imagens. Ela é capaz de, atribuindo importância a vários aspectos, diferenciar uma imagem de outra.

Redes neurais convolucionais são bastante parecidas com redes neurais simples, pois, da mesma forma, possuem pesos e bias. Porém, diferentemente das redes apresentadas anteriormente, não há um peso para cada neurônio que o conecte com a próxima camada, ou seja, uma camada completamente conectada, e sim, um conjunto de pesos com que é feita uma operação de convolução. Dessa forma, a quantidade de pesos a serem calculados é bem menor. 

Além disso, redes convolucionais são capazes de aprender o comportamento de filtros usados para obter features, diminuindo assim o pré processamento.

A seguir, serão explicadas algumas camadas de uma rede neural convolucional.

### Camada Convolucional

Como o nome já diz, é nessa camada em que ocorre a convolução. É definido um tamanho de kernel e a quantidade. A convolução será aplicada usando e, para cada kernel, um mapa de características será gerado.

### Camada de Pooling

Essa camada é aplicada posteriormente a uma camada convolucional. Seu intuito pricipal é condensar as infromações obtidas na camada anterior. Ela recebe como entrada o mapa de características da camada convolucional e prepara um mapa de características condensadas. Dessa forma, cada unidade da camada de pooling resume uma região da camada que deu origem a ela. 

Uma abordagem comum para o pooling é o Max-pooling, em que, para cada região, geralmente 2x2, a maior ativação é considerado. Dessa forma, o tamanho do mapa de recurso é reduzido a um quarto de seu tamanhgo original. Contudo, esse não é o único procedimento, outro comum é o chamado Pooling L2, em que o valor final corresponde a à raiz quadrada da soma dos quadrados das ativações.

<img src="https://perso.mines-paristech.fr/fabien.moutarde/ES_MachineLearning/TP_convNets/pool.png" alt="drawing" width="500"/>

### Camada de Saída

Essa é a camda final da rede. Se for um problema de classificação ou regressão, é ideal que essa camada não seja unidimensional, assim, muitas vezes, é preciso ter uma tranformação antes de se chegar a essa camadaa. Além disso, geralmente, essa camada é totalmente conectada com a anterior.

# Aplicações com Redes Neurais Artificiais

## Rede Neural Multicamadas com Scikit-Learn

Para a implementação de uma rede neural desse tipo, é aconselhável a utilização de bibliotecas que foram desenvolvidas para aplicação de tais métodos. 

Escolhemos a base [MNIST](http://yann.lecun.com/exdb/mnist/) para exemplificar o uso da biblioteca Scikit Learn no processamento e obtenção de resultados usando o [MPLClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html), que é a implementação do Scikit para uma rede neural multicamada. Os arquivos da base devem ser [baixados](https://www.kaggle.com/oddrationale/mnist-in-csv) e colocados no mesmo diretório que esse código.

In [0]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [0]:
# Criamos o dataframe
# Para isso, é importado os arquivos .csv de treinamento e teste

path = "mnist_train.csv"
mnist_data = pd.read_csv(path)

path_test = "mnist_test.csv"
mnist_test = pd.read_csv(path_test)

Agora, podemos verificar como os dados estão dispostos no dataframe.

Temos que a primeira coluna representa a classe da imagem, enquanto que as colunas seguintes representam o valor de cada pixel da imagem.

In [0]:
print(mnist_data)

       5  0  0.1  0.2  0.3  0.4  ...  0.612  0.613  0.614  0.615  0.616  0.617
0      0  0    0    0    0    0  ...      0      0      0      0      0      0
1      4  0    0    0    0    0  ...      0      0      0      0      0      0
2      1  0    0    0    0    0  ...      0      0      0      0      0      0
3      9  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
59994  8  0    0    0    0    0  ...      0      0      0      0      0      0
59995  3  0    0    0    0    0  ...      0      0      0      0      0      0
59996  5  0    0    0    0    0  ...      0      0      0      0      0      0
59997  6  0    0    0    0    0  ...      0      0      0      0      0      0
59998  8  0    0    0    0    0  ...      0      0      0      0      0      0

[59999 rows x 785 columns]


In [0]:
# Escolhemos os dados necessários para o treinamento para a variavel X
X_train = mnist_data.iloc[:, 1:]
X_test = mnist_test.iloc[:, 1:]

# Colocamos a coluna de classes na variavel y
y_train = mnist_data.iloc[:, 0]
y_test = mnist_test.iloc[:, 0]

Agora que estamos já preparados, podemos realizar o treinamento em si, utilizando a função que executa a rede neural multicamadas (MLPClassifier).

Para entender melhor seu funcionamento, devemos conhecer seus parâmetros:


*   hidden_layer_sizes: Permite escolher o número de camadas e neurônios das camadas ocultas.
*   max_iter: Define número de épocas. Default = 200.
*   solver: Método de solução dos pesos, sendo ‘lbfgs’, ‘sgd’ ou ‘adam’. No geral, conseguem os mesmos resultados, mas cada um é mais indicado dependendo do tamanho do dataset. Default = ’adam’.
* learning_rate: A taxa de aprendizagem pode ser definida como: ‘constant’, taxa constante, ‘invscaling’, taxa diminui a cada época por um fator determinado, e ‘adaptive’, a taxa diminui quando a função de erro para de diminuir. 






In [0]:
# Escolhemos duas camadas ocultas com tamanhos 100 e 20 neurônios, e o numero máximo de iterações como 3000.
mlp = MLPClassifier(hidden_layer_sizes=(1000, 20), max_iter=3000)
# Executamos o treinamento
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(50, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
# Executamos as predições
mlp_prediction = mlp.predict(X_test)

Podemos realizar a verificação dos resultados através das funções de métricas presentes na biblioteca Sklearn:

In [0]:
# Podemos imprimir a matriz de confusão encontrada
print(confusion_matrix(y_test,mlp_prediction))

# E também um relatório completo com cada métrica para análise
print(classification_report(y_test,mlp_prediction))

[[ 971    0    3    0    0    0    3    1    2    0]
 [   1 1099   11    4    0    0    2    2   16    0]
 [   1    0 1020    4    2    0    0    2    3    0]
 [   0    0    7  993    1    5    0    1    3    0]
 [   4    0    2    1  961    1    4    5    1    3]
 [   6    0    2   17    1  858    2    0    4    2]
 [   9    2    0    1    4    9  931    0    2    0]
 [   0    1   13   11    7    0    0  985    0   10]
 [   7    1   10    5    2    5    3    1  932    8]
 [   5    1    1    9   18    1    0    4    6  964]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       1.00      0.97      0.98      1135
           2       0.95      0.99      0.97      1032
           3       0.95      0.98      0.97      1010
           4       0.96      0.98      0.97       982
           5       0.98      0.96      0.97       892
           6       0.99      0.97      0.98       958
           7       0.98      0.96   

In [0]:
# Por fim, imprimimos apenas a acurácia alcançada, para visualização de um maior número de casas decimais
print("A acurácia foi de",accuracy_score(y_test, mlp_prediction))

A acurácia foi de 0.9714971497149715


**Nos** testes realizados, foram encontrados:


*   Rede com 300 camadas ocultas com 20 neurônios cada - Acurácia: 97,40%
*   Rede com 100 camadas ocultas com 20 neurônios cada - Acurácia: 97,21%
*   Rede com 100 camadas ocultas com 10 neurônios cada - Acurácia: 96,14%
*   Rede com 1000 camadas ocultas com 20 neurônios cada - Acurácia: 97,14%


## Exemplo de Rede Convolucional usando Keras

A seguir temos um exemplo de rede convolucional usando a biblioteca [Keras](https://keras.io/). Essa biblioteca usa [Tensorflow](https://www.tensorflow.org/overview) como backend e foi escolhida por ter implemetadas formas fáceis e poderosas de se criar uma rede convolucional.


Como redes convolucionais são muito boas para se trabalhar com imagens, foi escolhida uma base de dados de imagens para ser usada no exemplo.
A base de dados usada foi a [COVID-19 Radiography Database](https://www.kaggle.com/tawsifurrahman/covid19-radiography-database), que contém imagens de raio-X de pacientes com Covid-19, pacientes saudáveis e pacientes com pneumonia causada por outro tipos de vírus. 

As imagens foram separadas em treinamento, aproximadamente 50% do total, validação, 25%, e teste, 25%, sempre mantendo a proporção das classes. As imagens de treinamento foram colocadas em um diretório chamado "train" e separadas por classe em sub-diretórios diferentes. As imagens de validação foram colocadas em um diretório chamado "validation". E as de teste foram colocadas no diretório "test", também separadas por classe em sub-diretórios. Todas as pastas devem estar no mesmo diretório que o código.

O código foi testado em uma máquina com processador Intel core i7 64bits, 32GiB de memoria, sistema operacional Linux Xubuntu 20.04 64 bits e keras com tensorflow em backend versão 2.3.0 e tensorflow versão 2.0.0

In [0]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [0]:
# Inicializando um modelo sequencial
model = Sequential()

# Camada convolucional
model.add(Conv2D(filters=32, kernel_size=(7,7), input_shape=(128,128,1), activation='relu'))

# Camada de pooling
model.add(MaxPooling2D(pool_size = (2, 2)))

# Adicionando mais camadas
model.add(Conv2D(filters=20, kernel_size=(3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

# Transformando as camadas 2D para 1D
model.add(Flatten())

# Deixando a camada totalmente conectada
model.add(Dense(units = 100, activation = 'relu'))
model.add(Dense(units = 3, activation = 'sigmoid'))

# Compilando a rede
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 122, 122, 32)      1600      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 61, 61, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 59, 59, 20)        5780      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 29, 29, 20)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 16820)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               1682100   
_________________________________________________________________
dense_2 (Dense)              (None, 3)                

In [0]:
# Pre processamento das imagens
train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2,zoom_range = 0.2, horizontal_flip = True)
validation_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('train',target_size = (128, 128), batch_size = 32, class_mode = 'categorical', color_mode='grayscale')
validation_set = validation_datagen.flow_from_directory('validation',target_size = (128, 128), batch_size = 32, class_mode = 'categorical', color_mode='grayscale')

print('*********************INICIO DO TREINAMENTO*************************')

# Executando o treinamento
model.fit(training_set, epochs = 50, validation_data = validation_set, validation_steps = 20)
model.save_weights('cnn_covid.h5')

print('*********************FIM DO TREINAMENTO*************************')


# Etapa de teste
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('test',target_size = (128, 128), batch_size = 32, class_mode = 'categorical', color_mode='grayscale')

print('*********************INICIO DO TESTE*************************')

score = model.evaluate(test_set, verbose=True)

print('*********************FIM DO TESTE*************************')

print("Test loss:", score[0])
print("Test accuracy:", score[1])



Ao fim do processamento na máquina descrita acima, obtivemos:
* Acurácia da validação: 0.9443
* Acurácia do teste: 0.9133

O tempo de treinamento foi de aproximadamente 17min com uma média de 20s por época.

## Mãos a Obra: Como implementar sua própria rede neural?

Para quem gosta de entender como as coisas funcionam de verdade, faremos aqui uma implementação de uma rede neural simples.

### Camada

A estrutura básica da nossa implementação da rede neural é a camada. A camada tem como componentes básicos a matriz de pesos e o vetor de bias.


![alt text](camada.png)

Na matriz de pesos, cada linha representa um neurônio dessa camada. E cada elemento dessa linha representa um peso para dada entrada da camada, que são inicializados de forma aleatória. O vetor de bias é uma matriz coluna em que cada elemento é o bias de um velor da camada.

```
class Layer:
  def __init__(self, n_neurons, n_inputs, is_output_layer=False):
    # Número de neurônios da camada
    self.size = n_neurons
    # Matriz de pesos
    self.weights = np.random.rand(n_neurons, n_inputs,)
    # Vetor de bias
    self.biases = np.random.rand(n_neurons,1)
    self.is_output_layer = is_output_layer
```


#### **Forward Pass**

Forward pass é nome que se dá para a função que faz a operação:

$$ Saida=f\left( \left( \sum _{ i=1 }^{ n }{ { x }_{ i }{ w }_{ i } }  \right) +b \right) $$

em todos os neurônios da rede. Essa operação nada mais é que a multiplicação da matriz de pesos da camada pelo vetor de entrada dessa camada e a aplicação da função de ativação, que no nosso caso é a função sigmoide.

Na nossa implementação, para poupar trabalho na etapa de backward pass, também calculamos a derivada da função de ativação aplicada na saída da camada.



```
  def forward_pass(self, inputs):
    def sigmoid(x): 
      return 1 / (1 + np.exp(-x))
    # Aplica função em todos os elementos do vetor
    sigmoid_v = np.vectorize(sigmoid)

    def sigmoid_derivative(x): 
      return x * (1 - x)
    sigmoid_derivative_v = np.vectorize(sigmoid_derivative)

    # Aplicação dos pesos e bias de cada neurônio
    z = np.dot(self.weights, inputs) + self.biases
    # Cálculo da saída da rede
    self.output = sigmoid_v(z)
    # Cálculo da derivada da função de ativação aplicada na saída
    self.delta_output = sigmoid_derivative_v(self.output)

```

#### **Backward Pass**

A função backward_pass realiza o algoritmo de *Backpropagation* em cada camada da nossa rede.

A princípio, os pesos e bias utilizados para as primeiras predições foram determinados de forma aleatória, causando divergências nos valores esperados como saída da rede. Tendo em vista o erro encontrado no resultado final, podemos utilizar o método de retro-propagação para que os pesos em cada neurônio sejam ajustados de forma a alcançar os valores ideiais que resultariam em predições corretas. Sendo bastante improvável que seja alcançado valores aceitaveis em uma primeira retro-propagação, todo esse ciclo de propagação e retro-propagação é repetido n-vezes até que o erro produzido seja pequeno o suficiente.

A [formulação matemática](https://towardsdatascience.com/the-maths-behind-back-propagation-cf6714736abf) desse algoritmo é um pouco complicada, aqui iremos mostrar apenas a sua implementação.

A função de backward_pass irá passar pela rede de trás para frente calculando o erro que a sua operação gerou no resultado final. Esse erro irá mais tarde guiar quanto e em que sentido a rede deve alterar seus pesos para diminuir o valor da função de custo. 

A função de custo que utilizamos é:

$$ Funcao\_ de\_ Custo = \frac { 1 }{ 2 } \sum _{ i=1 }^{ n }{ { (saida-valor\_ esperado) }^{ 2 } }  $$

Usamos a derivada da função de custo para calcular o delta que indica o quanto a variação de cada peso irá afetar a saída.

Esse delta é:

$$ delta = derivada\_ funcao\_ de\_ custo\cdot derivada\_ funcao\_ de\_ ativacao $$

Para a camada de saída essa derivada é:

$$ derivada\_ funcao\_ de\_ custo = saida-valor\_ esperado $$

Para as demais camadas:

$$ derivada\_ funcao\_ de\_ custo = matriz\_ de\_ pesos\cdot delta\_ camada\_ a\_ direita $$

A derivada da função de ativação foi calculada e armazenada na função forward pass.



```
  def backward_pass(self, y, rightLayer):
    # Para a camada de saída
    if self.is_output_layer:
      # Derivada da função de custo
      error =  self.output - y
      self.delta = np.atleast_2d(error * self.delta_output)
    # Para as outras camadas
    else:
      self.delta = np.atleast_2d(rightLayer.weights.T.dot(rightLayer.delta)*self.delta_output)
    return self.delta
```




#### **Update**

A função update realiza a atualização dos pesos e bias da camada, com base em:

$$ novos\_ pesos=taxa\_ de\_ aprendizagem\cdot (delta\cdot entrada\_ da\_ camada) $$

$$ novos\_ bias=taxa\_ de\_ aprendizagem\cdot delta $$

```
 def update(self, learning_rate, left_output):
    layer_input = np.atleast_2d(left_output)
    delta = np.atleast_2d(self.delta)
    self.weights -= learning_rate * delta.dot(layer_input.T)
    self.biases -= learning_rate * delta
```



Assim, temos a classe Layer.

In [0]:
class Layer:
  def __init__(self, n_neurons, n_inputs, is_output_layer=False):
    # Número de neurônios da camada
    self.size = n_neurons
    # Matriz de pesos
    self.weights = np.random.rand(n_neurons, n_inputs,)
    # Vetor de bias
    self.biases = np.random.rand(n_neurons,1)
    self.is_output_layer = is_output_layer
    
  def forward_pass(self, inputs):
    def sigmoid(x): 
      return 1 / (1 + np.exp(-x))
    # Aplica função em todos os elementos do vetor
    sigmoid_v = np.vectorize(sigmoid)

    def sigmoid_derivative(x): 
      return x * (1 - x)
    sigmoid_derivative_v = np.vectorize(sigmoid_derivative)

    # Aplicação dos pesos e bias de cada neurônio
    z = np.dot(self.weights, inputs) + self.biases
    # Cálculo da saída da rede
    self.output = sigmoid_v(z)
    # Cálculo da derivada da função de ativação aplicada na saída
    self.delta_output = sigmoid_derivative_v(self.output)

  def backward_pass(self, y, rightLayer):
    # Para a camada de saída
    if self.is_output_layer:
      # Derivada da função de custo
      error =  self.output - y
      self.delta = np.atleast_2d(error * self.delta_output)
    # Para as outras camadas
    else:
      self.delta = np.atleast_2d(rightLayer.weights.T.dot(rightLayer.delta)*self.delta_output)
    return self.delta

  def update(self, learning_rate, left_output):
    layer_input = np.atleast_2d(left_output)
    delta = np.atleast_2d(self.delta)
    self.weights -= learning_rate * delta.dot(layer_input.T)
    self.biases -= learning_rate * delta

### Rede Neural

A classe Network monta a rede neural usando as camadas. Ela recebe o tamanho do vetor de entradas, um vetor de inteiros que indica a quantidade de neurônios de cada camada e a taxa de aprendizagem da rede.

In [0]:
class Network:
  def __init__(self, n_inputs, layers_size, learning_rate):
    # A rede é composta por uma lista de camadas
    self.layers = [] 
    # Número de camadas
    self.size = len(layers_size)
    # Taxa de Aprendizagem
    self.learning_rate = learning_rate

    # Preenche a rede com camadas
    for i in range(len(layers_size)):
      if i == 0: # Primeira camada
        self.layers.append(Layer(layers_size[i], n_inputs))
      elif i == len(layers_size)-1: # Última camada
        self.layers.append(Layer(layers_size[i], layers_size[i-1], True))
      else: # Demais Camadas
        self.layers.append(Layer(layers_size[i], layers_size[i-1]))

  # Aplica o algoritmo de backpropagation para um exemplo de treinamento.
  def train(self, x, y):
    # Aplica forward_pass
    for i in range(self.size):
      if i == 0:
         self.layers[i].forward_pass(x)
      else:
         self.layers[i].forward_pass(self.layers[i-1].output)
    # Aplica backward_pass
    for i in range(1, self.size+1):
      if i == 1:
        self.layers[-i].backward_pass(y, None)
      else:
        self.layers[-i].backward_pass(y, self.layers[-i+1])
    # Aplica update
    for i in range(1, self.size+1):
      if i == self.size:
        self.layers[-i].update(self.learning_rate, x)
      else:
        self.layers[-i].update(self.learning_rate, self.layers[-i-1].output)

    # Retorna o valor da função de custo para o exemplo de treinamento
    return  sum(np.exp2(self.layers[-1].output - y))/2

  # Aplica o treinamento para vários exemplos iterando o número de épocas dadas
  def fit(self, x, y, epochs):

    for j in range(epochs):
      error = 0
      for i in range(len(x)):
        inputs = np.resize(x[i], (len(x[i]),1))
        outputs = np.resize(y[i], (len(y[i]),1))
        error += self.train(inputs,outputs)

      # Média do resultado da função de custo para todos os exemplos de treinamento  
      error = error/len(x)

      self.predict(x,y)
    print("Loss {} Acurácia {}%".format(error, self.accuracy*100))


  # Faz a predição dos exemplos de treinamento aplicados nos valores atuais dos pesos da rede
  def predict(self, x, y):
    accuracy = 0
  
    for j in range(len(x)):
      inputs = np.resize(x[j], (len(x[j]),1))
      outputs = np.resize(y[j], (len(y[j]),1))

      # Aplica forward_pass
      for i in range(self.size):
        if i == 0:
          self.layers[i].forward_pass(inputs)
        else:
          self.layers[i].forward_pass(self.layers[i-1].output)

      y_pred = self.layers[-1].output.flatten()
      y_real = y[j].flatten()

      # Compara saída com resultado esperado
      if self.classify(y_pred, y_real):
        accuracy += 1

    self.accuracy = accuracy/len(x)
    return self.accuracy

  
  def classify(self, y_pred, y_real):
    # Se a sua saída é binária, aplica limiar
    if(len(y_pred)==1):
      if(y_pred[0]>0.5 and y_real[0]==1) or (y_pred[0]<0.5 and y_real[0]==0):
        return True
      return False
    # Se a saída é um vetor, verifica qual elemento possui maior probabilidade
    return np.argmax(y_pred) == np.argmax(y_real)

### Testando a Rede

Para testar o funcionamento da nossa rede, vamos aplicá-la na base íris e verificar se após o treinamento, ela consegue reduzir o erro e aprender a diferenciar as espécies da flor íris.

In [0]:
import numpy as np
from sklearn import datasets 
from pandas import get_dummies

# Carregamos o dataset
iris = datasets.load_iris()
x = np.array(iris.data[:, :4])  # we only take the first two features.
y = np.array(get_dummies(iris.target).values)

# A rede irá receber como entrada um vetor de 4 elementos
input_size = 4
# A rede possui uma cama oculta de 5 neurônios e uma camada de saída de 3 neurônios,
# que indicam as 3 espécies da base iris
layers_size = [5, 3]


net = Network(input_size, layers_size, 0.1)
net.fit(x,y,300)

Loss [1.50664466] Acurácia 96.66666666666667%


Após 300 épocas, nossa rede consegue acertar 96% dos exemplos de treinamento. Esse número pode variar a cada teste porque os pesos iniciais são aleatórios. O número de épocas também pode melhorar a precisão do modelo.

# Referências Bibliográficas

* http://deeplearningbook.com.br/o-perceptron-parte-1/
* https://towardsdatascience.com/perceptron-learning-algorithm-d5db0deab975
* http://deeplearningbook.com.br/a-arquitetura-das-redes-neurais/
* https://lamfo-unb.github.io/2017/06/18/itro-ao-deep-learning/
* https://www.youtube.com/watch?v=aircAruvnKk
* https://www.youtube.com/watch?v=IHZwWFHWa-w
* https://imasters.com.br/data/um-mergulho-profundo-nas-redes-neurais-recorrentes
* http://deeplearningbook.com.br/construindo-uma-rede-neural-com-linguagem-python/
* https://jamesmccaffrey.wordpress.com/2019/04/27/the-difference-between-linearly-separable-data-and-a-linear-classifier-in-machine-learning/
* https://scikit-learn.org/stable/modules/neural_networks_supervised.html
* https://analyticsindiamag.com/a-beginners-guide-to-scikit-learns-mlpclassifier/
* https://imasters.com.br/data/um-mergulho-profundo-nas-redes-neurais-recorrentes


# Referências das Imagens

* https://www.brainlatam.com/blog/neurolab-6-o-que-sao-os-neuronios-e-como-eles-se-comunicam-1118
* https://mc.ai/activation-function-and-its-types/
* https://imasters.com.br/data/um-mergulho-profundo-nas-redes-neurais-recorrentes
* https://embarc.org/embarc_mli/doc/build/html/MLI_kernels/pooling_max.html

